package fpt.capstone.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum Action {

    USER_LOGIN("USER_LOGIN"),
    USER_LOGOUT("USER_LOGOUT"),
    PASSWORD_RESET("PASSWORD_RESET"),
    CHANGE_PASSWORD("CHANGE_PASSWORD"),
    ILLEGAL_REQUEST("ILLEGAL_REQUEST"),
    CREATE_APPLICATION("CREATE_APPLICATION"),
    APPLICATION_DELETE("APPLICATION_DELETE"),
    CREATE_USER("CREATE_USER"),
    DELETE_USER("DELETE_USER"),
    CHANGE_ROLE("CHANGE_ROLE"),
    CREATE_ROLE("CREATE_ROLE"),
    CREATE_RIGHT("CREATE_RIGHT"),
    UPDATE_USER("UPDATE_USER"),
    PERMISSION_UPDATE("PERMISSION_UPDATE"),
    RIGHT_CREATE("RIGHT_CREATE"),
    RIGHT_UPDATE("RIGHT_UPDATE"),
    SUPPORT_REQUEST_CREATE("SUPPORT_REQUEST_CREATE"),
    SUPPORT_REQUEST_REPLY("SUPPORT_REQUEST_REPLY"),
    SUPPORT_REQUEST_STATUS_UPDATE("SUPPORT_REQUEST_STATUS_UPDATE"),
    GET_APPLICATIONS("GET_APPLICATIONS"),
    UPDATE_APPLICATION("UPDATE_APPLICATION"),
    OCR_SCAN("OCR_SCAN"),
    DECISION_CREATE("DECISION_CREATE"),
    BENIFICIARY_CREATE("BENIFICIARY_CREATE"),
    BENIFICIARY_GET("BENIFICIARY_GET"),
    WOUNDER_SOLDIER_CREATE("WOUNDER_SOLDIER_CREATE"),
    WOUNDER_SOLDIER_GET("WOUNDER_SOLDIER_GET"),
    RELATIVE_CREATE("RELATIVE_CREATE"),
    RELATIVE_GET("RELATIVE_GET"),
    ADDITIONAL_DOCUMENT_CREATE("ADDITIONAL_DOCUMENT_CREATE"),
    ADDITIONAL_DOCUMENT_GET("ADDITIONAL_DOCUMENT_GET"),
    ADDITIONAL_DOCUMENT_UPDATE("ADDITIONAL_DOCUMENT_UPDATE"),
    ADDITIONAL_DOCUMENT_DELETE("ADDITIONAL_DOCUMENT_DELETE"),
    BACKUP_COMPLETE("BACKUP_COMPLETE"),
    RESTORE_COMPLETE("RESTORE_COMPLETE"),
    USER_DEACTIVATE("USER_DEACTIVATE"),
    USER_ACTIVATE("USER_ACTIVATE"),
    ;

    private String action;
}
