package fpt.capstone.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum Table {

    USER("USERS"),
    SYSTEM_LOG("SYSTEM_LOGS"),
    SPONSOR("SPONSORS"),
    ROLE("ROLES"),
    RIGHT("RIGHTS"),
    PERMISSION("PERMISSIONS"),
    GOODS_INVENTORY("GOODS_INVENTORIES"),
    GOODS_DISTRIBUTION("GOODS_DISTRIBUTIONS"),
    ELIGIBILITY_CRITERIA("ELIGIBILITY_CRITERIAS"),
    DONATION("DONATIONS"),
    DISTRIBUTION_RECORD("DISTRIBUTION_RECORDS"),
    DECISION_DOCUMENT("DECISION_DOCUMENTS"),
    BENIFICIARY("BENIFICIARIES"),
    BENIFIT_RULE("BENIFIT_RULES"),
    BENIFIT_HISTORY("BENIFIT_HISTORY"),
    ARTICLE("ARTICLES"),
    APPLICATION("APPLICATIONS"),
    ADDITIONAL_DOCUMENT("ADDITIONAL_DOCUMENTS"),
    WOUNDER_SOLDIER("WOUNDER_SOLDIERS"),
    RELATIVE("RELATIVES"),
    CHAPTER("CHAPTERS"),
    SUPPORT_REQUEST("SUPPORT_REQUESTS"),
    BACKUP("BACKUPS"),
    SUPPORT_ITEM("SUPPORT_ITEMS"),
    INBOUND_RECEIPT("INBOUND_RECEIPTS"),
    STOCK_ADJUSTMENT("STOCK_ADJUSTMENTS"),
    FUND_USAGE_PLAN("FUND_USAGE_PLANS"),
    ITEM_ALLOCATION_PLAN("ITEM_ALLOCATION_PLANS"),
    ITEM_ALLOCATION_PLAN_LINE("ITEM_ALLOCATION_PLAN_LINES"),
    DISTRIBUTION("DISTRIBUTIONS"),
    RESOURCE_ATTACHMENT("RESOURCE_ATTACHMENTS"),
    ;

    private String tableName;
}
