server.port=8088
server.servlet.context-path=/capstone
spring.application.name=capstone

#DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#DB
spring.datasource.url=jdbc:mysql://localhost:1435/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

#ACCOUNT
spring.datasource.username=root
spring.datasource.password=123456

#CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email


