# Database Local
spring.datasource.url=jdbc:mysql://localhost:1435/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

# Redis Local
spring.data.redis.host=localhost
spring.data.redis.port=6379
